### ISSUE TITLE
code to plot the graph in the paper?

### ISSUE THREAD

**Issue by donwany** [IBM/fl-arbitrary-participation#1]
Is there a way you can give out the code to make the plots in the paper?

**Comment by shiqiangw** [comment]
Here is an example of the plotting code: [plot_periodic_main_neurips22.zip](https://github.com/IBM/fl-arbitrary-participation/files/14939356/plot_periodic_main_neurips22.zip)

The first part of the code needs to be changed to match with your directory and file names.

**Comment by donwany** [comment]
> Here is an example of the plotting code: [plot_periodic_main_neurips22.zip](https://github.com/IBM/fl-arbitrary-participation/files/14939356/plot_periodic_main_neurips22.zip)
> 
> The first part of the code needs to be changed to match with your directory and file names.

Thanks
